### ISSUE TITLE
Handle 404 from the API

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/coverage-space-cli#35]
```
$ coverage.space foobar unit 42
Traceback (most recent call last):
  File "/Users/Browning/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/site-packages/coveragespace/cli.py", line 96, in call
    data = response.json()
  File "/Users/Browning/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/Browning/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/site-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/Users/Browning/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/site-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/Users/Browning/.pyenv/versions/3.6.0/Python.framework/Versions/3.6/lib/python3.6/site-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jacebrowning** [comment]
Or simply require the slug to contain a slash.
